### ISSUE TITLE
Progress isn't reported for mp4 files

### ISSUE THREAD

**Issue by mrbeck02** [Codeuctivity/mencoder-sharp#1]
It looks like the progress reported by Mencoder when translating a mp4 file is always 0% in all of the standard output messages.  However, the number of seconds processed so far is listed.  Could you change the code so it gets the file length and then reports the progress based on the seconds processed so far vs the whole file size?

**Comment by stesee** [comment]
I can not reproduce your problem (i debugged TestMethodSyncEncode of https://github.com/Codeuctivity/mencoder-sharp/blob/master/UnitTestMencoderSharp/UnitTest1.cs and saw a changing value for progress). Send me some testdata, if you still have problems.

**Comment by mrbeck02** [comment]
Thanks for looking into this.  The issue I'm having is converting from mp4 to avi, not the other way around.  I set a conditional breakpoint in backgroundWorker1_ProgressChanged to fire whenever progress != 0.  It never fires.

The sample mp4 video I'm using is located here: http://techslides.com/demos/sample-videos/small.mp4 

The file gets translated correctly, it's just the progress that isn't reported.

The problem seems to be with mencoder itself.  The standard output from mencoder has 0% progress reported.  Put a breakpoint in MencoderAsync at the following line:

progressReporting = parseAndReportProgress(worker, standardOut, progressReporting);

and see that the standard out has (0%) in the percent.

**Comment by stesee** [comment]
I fixed the error by replacing the used binary of mencoder with the latest (MPlayer r37905 for 32-bit Windows) build.

Do you mind that i use your sample video file small.mp4 in the unittests and to publish it beside of the code?

**Comment by mrbeck02** [comment]
Great, thanks!  The video isn't mine, I found it here: http://techslides.com/sample-webm-ogg-and-mp4-video-files-for-html5

The article says "Feel free to use the following files for whatever you need:"  So I guess you can use it.

Thanks again
